### ISSUE TITLE
Maelstrom_Motif2TF: Maximum variation/correlation link broken & Returned objects incomplete

### ISSUE THREAD

**Issue by Rebecza** [JGASmits/AnanseSeurat#20]
Working on this! PR in a bit.

What happens is Maelstrom_Motif2TF:
- Breaks when chosing max_var or max_cor as way of linking Motifs 2 TFs. 
- Returns only anticorrelating matrix in the `return_df = T` option (matrix is emptied in the loop over Cor and AntiCor).

**Comment by JGASmits** [comment]
Included the PR & added necisary Matrix dependency in #76b8902
