### ISSUE TITLE
Locating the inf dir 

### ISSUE THREAD

**Issue by sylestiel** [JGASmits/AnanseSeurat#30]
Hi,

 Could you provide some guidance on how to specify the location of the influence dir for the function
import_seurat_scANANSE()?
This is the layout of my anansnake folder:

<img width="348" alt="Screenshot 2023-08-10 at 12 50 41 PM" src="https://github.com/JGASmits/AnanseSeurat/assets/64283689/7a117977-5f5b-4c9b-9ef2-b64b898f42a0">

Thanks!

**Comment by JGASmits** [comment]
Hi Sylestiel,

Thanks for your patience, i was on holiday.
You can specify where the influence folder appears via:
config_scANANSE(output_dir ='location_of_a_folder')
After you run anansnake the influence directory should subsequently be:
'location_of_a_folder/influence'
What this function does under the hood is specifying the location of the anansnake output.
In the anansnake config file (result_dir: location_of_a_folder)
After running anansnake the influence files should be present in this folder (which are subsequently loaded by the import function).

Greetings

JGA Smits
